appname: my-blog

server:
  port: 3000
  sessionAge: 2
  useCors: false
  dist: "./front-end/dist"

db:
  type: mysql
  address: localhost
  port: 3306
  name: blog
  user: root
  password: root-password
  parseTime: true

